spring:
  datasource:
    username: root
    password: 12345Zz##
    url: jdbc:mysql://localhost:3306/transactions_db
  jpa:
    show-sql: true
    hibernate :
      ddl-auto: create

logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: debug

